name: Patrick Cines
favicon: null
layout_spectrum: 0.8
title: Patrick Cines
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#808080'
    - '#bfbfbf'
    - '#cccccc'
    - '#efefef'
  brandStrength: 0.6875
  lightness: 0.5
  saturation: 0.5
  rhythmicContrast: 0.5
purpose:
  - name: shares
    item: null
    url: null
