typography_spectrum: 0.47003
color:
  brandColors:
    - '#050505'
    - '#ffffff'
    - '#80807e'
    - '#3e4651'
    - '#cacbcc'
  brandStrength: 0.875
  lightness: 0.6875
  saturation: 0.8125
  rhythmicContrast: 0.75
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.9781
analytics:
  google: null
  facebook: null
  twitter: null
name: Patrick Cines
cta:
  domain: null
  bucket: null
  version: null
favicon: null
title: Patrick Cines
purpose: []
